# Generated by Django 5.0.3 on 2024-03-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlivapp', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='mite_img'),
        ),
    ]
