# Generated by Django 5.0.3 on 2024-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlivapp', '0006_alter_business_address_1_alter_business_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(default='Sample Business', max_length=50),
            preserve_default=False,
        ),
    ]
