# Generated by Django 5.0.3 on 2024-03-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlivapp', '0007_business_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='mite_videos'),
        ),
    ]
