# Generated by Django 5.0.3 on 2024-03-30 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlivapp', '0008_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='mite_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['asf', 'avi', 'gif', 'm4v', 'mkv', 'mov', 'mp4', 'mpeg', 'mpg', 'ts', 'wmv', 'webm'])]),
        ),
    ]
